In [3]:
import numpy as np
a = np.array([[1,0],[0,1]])
a 
#np.matumul(A,B) multiplica matrices
from itertools import permutations
p = permutations([1,2,3,4])
print(list(p))

#EJEMPLO
#Se cambian las filas
A = np.array([[0,1,0],[1,0,1],[0,1,0]])
B = np.array([[0,0,1],[0,0,1],[1,1,0]])
p = np.array([[1,0,0],[0,0,1],[0,1,0]])

(p@A)@p == B
((p@A)@p == B).all()
A

[(1, 2, 3, 4), (1, 2, 4, 3), (1, 3, 2, 4), (1, 3, 4, 2), (1, 4, 2, 3), (1, 4, 3, 2), (2, 1, 3, 4), (2, 1, 4, 3), (2, 3, 1, 4), (2, 3, 4, 1), (2, 4, 1, 3), (2, 4, 3, 1), (3, 1, 2, 4), (3, 1, 4, 2), (3, 2, 1, 4), (3, 2, 4, 1), (3, 4, 1, 2), (3, 4, 2, 1), (4, 1, 2, 3), (4, 1, 3, 2), (4, 2, 1, 3), (4, 2, 3, 1), (4, 3, 1, 2), (4, 3, 2, 1)]


array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]])

In [4]:
A1 = np.array([
    [0,1,1,0,1],
    [1,0,0,1,1],
    [1,0,0,1,1],
    [0,1,1,0,1],
    [1,1,1,1,0]
])
B1 = np.array([
    [0,1,0,1,1],
    [1,0,1,0,1],
    [0,1,0,1,1],
    [1,0,1,0,1],
    [1,1,1,1,0]
])
L = iso(A1,B1)

La matriz de permutación es:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]]


In [89]:
B2 == P @ A2 @ P.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
U = np.array([
    [0, 1, 0, 1, 1, 1, 0, 1],
    [0, 0, 1, 0, 1, 1, 1, 0],
    [0, 0, 0, 1, 0, 1, 1, 1],
    [0, 0, 0, 0, 1, 0, 1, 1],
    [0, 0, 0, 0, 0, 1, 0, 1],
    [0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0]
])
U = U + U.T
U

array([[0, 1, 0, 1, 1, 1, 0, 1],
       [1, 0, 1, 0, 1, 1, 1, 0],
       [0, 1, 0, 1, 0, 1, 1, 1],
       [1, 0, 1, 0, 1, 0, 1, 1],
       [1, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 0, 1, 0, 1, 0],
       [0, 1, 1, 1, 0, 1, 0, 1],
       [1, 0, 1, 1, 1, 0, 1, 0]])

In [6]:
V = np.array([
    [0, 1, 1, 0, 1, 0, 1, 1],
    [0, 0, 1, 1, 0, 1, 0, 1],
    [0, 0, 0, 1, 1, 0, 1, 0],
    [0, 0, 0, 0, 1, 1, 0, 1],
    [0, 0, 0, 0, 0, 1, 1, 0],
    [0, 0, 0, 0, 0, 0, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0]
])
V = V + V.T
V

array([[0, 1, 1, 0, 1, 0, 1, 1],
       [1, 0, 1, 1, 0, 1, 0, 1],
       [1, 1, 0, 1, 1, 0, 1, 0],
       [0, 1, 1, 0, 1, 1, 0, 1],
       [1, 0, 1, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 1, 0, 1, 1],
       [1, 0, 1, 0, 1, 1, 0, 1],
       [1, 1, 0, 1, 0, 1, 1, 0]])

In [9]:
import networkx as nx

G1 = nx.from_numpy_array(U)
G2 = nx.from_numpy_array(V)
G1

print(nx.is_isomorphic(G1,G2))  # True o False


False


In [10]:
iso(U,V)

No se encontro matriz de permutación


In [12]:
x = np.array([
    [0, 1, 0, 0],
    [1, 0, 1, 0],
    [0, 1, 0, 1],
    [0, 0, 1, 0]
])
z = np.array([
    [0, 0, 0, 1],
    [0, 0, 1, 1],
    [0, 1, 0, 0],
    [1, 1, 0, 0]
])

In [7]:
def iso(A,B): 
    dim = list(A.shape)[0] #Dimensión de la matriz
    I = np.eye(dim)
    p = list(permutations(np.arange(0,dim)))
    encontro = False
    for i in range(0,len(p)):
        I = I[list(p[i])]
        if ((I@A)@I.T == B).all() == True:
           encontro = True
           print(f"La matriz de permutación es:\n {I}")
           return I
    if encontro == False:
        print("No se encontro matriz de permutación")


In [13]:
iso(z,x)

La matriz de permutación es:
 [[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


array([[1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [68]:

A2 = np.array([
    [0, 1, 1],  # conexiones del nodo 1 con 2 y 3
    [1, 0, 0],  # nodo 2 con 1
    [1, 0, 0]   # nodo 3 con 1
])

B2 = np.array([
    [0, 1, 0],  # conexiones del nodo a (que es 3) con c (1)
    [1, 0, 1],  # nodo c (que es 1) con a (3) y b (2)
    [0, 1, 0]   # nodo b (que es 2) con c (1)
])
iso(A2,B2)

La matriz de permutación es:
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [45]:
p = list(permutations(np.arange(0,2)))
print(len(p))
for i in range(0,len(p)):
    print(i)


2
0
1


In [56]:
iso(A,B)

La matriz de permutación es:
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
