In [ ]:
import numpy as np
from itertools import permutations

def iso(A,B): 
    dim = list(A.shape)[0] #Dimensión de la matriz
    I = np.eye(dim)
    p = list(permutations(np.arange(0,dim)))
    encontro = False
    for i in range(0,len(p)):
        I = I[list(p[i])]
        if ((I@A)@I.T == B).all() == True:
           encontro = True
           print(f"La matriz de permutación es:\n {I}")
           return I
    if encontro == False:
        print("No se encontro matriz de permutación")

### Ejemplo 1

In [3]:
x = np.array([
    [0, 1, 0, 0],
    [1, 0, 1, 0],
    [0, 1, 0, 1],
    [0, 0, 1, 0]
])
z = np.array([
    [0, 0, 0, 1],
    [0, 0, 1, 1],
    [0, 1, 0, 0],
    [1, 1, 0, 0]
])

iso(x,z)

La matriz de permutación es:
 [[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]


array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]])

### Ejemplo 2 (Del trabajo)

In [4]:
U = np.array([
    [0, 1, 0, 1, 1, 1, 0, 1],
    [0, 0, 1, 0, 1, 1, 1, 0],
    [0, 0, 0, 1, 0, 1, 1, 1],
    [0, 0, 0, 0, 1, 0, 1, 1],
    [0, 0, 0, 0, 0, 1, 0, 1],
    [0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0]
])
U = U + U.T

V = np.array([
    [0, 1, 1, 0, 1, 0, 1, 1],
    [0, 0, 1, 1, 0, 1, 0, 1],
    [0, 0, 0, 1, 1, 0, 1, 0],
    [0, 0, 0, 0, 1, 1, 0, 1],
    [0, 0, 0, 0, 0, 1, 1, 0],
    [0, 0, 0, 0, 0, 0, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0]
])
V = V + V.T

iso(U,V)


No se encontro matriz de permutación
